### ISSUE TITLE
How does tracer work with @Scheduled?

### ISSUE THREAD

**Issue by innokenty** [zalando/tracer#125]
I have a spring-boot project with tracer added (more details below). Configuration is just the default one, just the trace name is configured. I'm trying to get my trace value in a `@Scheduled` method, but I get `IllegalStateException: X-Flow-ID has not been started`.

Question: how is it supposed to work? I think the documentation on this is missing.

## Description

- I'm running on `spring-boot:1.4.6`.
- I have only `tracer-spring-boot-starter:0.16.0` in dependencies.
- I have configured only this single property for tracer: `tracer.traces.X-Flow-ID=flow-id`
- I have a `@Scheduled` method inside of which I'm calling `tracer.get("X-Flow-ID").getValue()` on an `@Autowired Tracer tracer` field.
- Autowiring works, but I get the following exception:
```
java.lang.IllegalStateException: X-Flow-ID has not been started
	at org.zalando.tracer.DefaultTracer.getAndCheckValue(DefaultTracer.java:102) ~[tracer-core-0.16.0.jar:na]
	at org.zalando.tracer.DefaultTracer.access$000(DefaultTracer.java:15) ~[tracer-core-0.16.0.jar:na]
	at org.zalando.tracer.DefaultTracer$1.getValue(DefaultTracer.java:68) ~[tracer-core-0.16.0.jar:na]
```

## Question
I didn't really find any docs of what a "support for scheduling" means. I'm sure I'm doing something wrong, but can you point out what's missing? I was expecting that the trace will be already initialized and I can just get it's value (and send in an outgoing request).

**Comment by whiskeysierra** [comment]
That sounds like the correct setup to me. Can you compare your setup to this [test](https://github.com/zalando/tracer/blob/master/tracer-spring-boot-starter/src/test/java/org/zalando/tracer/spring/SchedulingTest.java)? Maybe there is an obvious difference somewhere? Do you register a custom `TaskScheduler` or something? Maybe you can put some breakpoints in the [`SchedulingAutoConfiguration`](https://github.com/zalando/tracer/blob/master/tracer-spring-boot-starter/src/main/java/org/zalando/tracer/spring/TracerAutoConfiguration.java#L161)  to see whether it's executed correctly.

**Comment by innokenty** [comment]
I think the problem is in spring-boot version. The same code exactly works great on a fresh project running on spring-boot 2. It might be something else is different, but I don't really think so.

**Comment by innokenty** [comment]
It works on an empty project indeed. I think the scheduler configuration doesn't work properly in this case. Not sure why, but I think [the conditional `taskScheduler` bean](https://github.com/zalando/tracer/blob/master/tracer-spring-boot-starter/src/main/java/org/zalando/tracer/spring/TracerAutoConfiguration.java#L179) is simply not created. In my log I see only:
```
org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler - Initializing ExecutorService  'taskScheduler'
```
ANd no more relevant mentions of `taskScheduler`.

How is this supposed to work, if a bean with this name and type is already present?

**Comment by innokenty** [comment]
Ah! I think that's because our project had a stupid class like this:

```java
@Configuration
public class TaskSchedulerConfig {
    @Bean
    public ThreadPoolTaskScheduler taskScheduler() {
        return new ThreadPoolTaskScheduler();
    }
}
```

Why... why?!
Anyway, maybe it would a great idea to somehow make this configuration not conditional, but make it extend whatever schedulers there are already in the context.

And if someone stumbles upon that thread some day: check if you already have a taskScheduler bean defined, guys! It ain't gonna work!!

**Comment by Sam-Kruglov** [comment]
Just got the same error. Had to copy paste bean definition from `org.zalando.tracer.spring.TracerAutoConfiguration.AsyncAutoConfiguration#taskExecutor` without condition. Worked, thanks

**Comment by Sam-Kruglov** [comment]
@innokenty it doesn't make sense to have both `@Primary` and `@ConditionalOnMissingBean`

**Comment by Sam-Kruglov** [comment]
@whiskeysierra  it doesn't make sense to have both `@Primary` and `@ConditionalOnMissingBean`
