### ISSUE TITLE
Is tracer ready to support Zipkin?

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/tracer#18]
https://twitter.github.io/zipkin/Instrumenting.html

**Comment by whiskeysierra** [comment]
Trace and parent span id is easy, we just pass them along. Span id is tricky, since we need a new one for every outgoing request. Altogether we need a new generator for those. Flags and is-sampled should be straightforward.

**Comment by jbellmann** [comment]
Hi Willi,

maybe you already know it but I want to make you aware of [spring-cloud-sleuth](https://github.com/spring-cloud/spring-cloud-sleuth#spring-cloud-sleuth) where the spring team build an similar system that supports Zipkin. Maybe it's easier to integrate there instead of Zipkin directly.

**Comment by whiskeysierra** [comment]
Good idea. I added it to #26

**Comment by whiskeysierra** [comment]
Zipkin is trying to be way more than Tracer tries to. It includes timing and pre-defined as well as custom annotations/events. Tracer is solely built for log correlation and in theory it could support dependency analysis (assuming all logs are accessible from the same system). I'll close this now, because full Zipkin compatibility is not feasible, nor desired.
