### ISSUE TITLE
Settle on a name

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/tracer#209]
## Detailed Description

We should settle on one and only one name that is not overloaded already.

## Context

Given we follow the path outlined in #204 then we are in a somewhat fuzzy spot in terms of naming:

- This library is **historically called _Tracer_** because it was meant to target a very specific aspect of _distributed system **tracing**_.  
  The name was used consistently:
  - `tracer` repositoriy
  - `tracer-*` modules and artifacts
  - `org.zalando.tracer` package
  - `Tracer` main API
  - `TracerFilter`
  - `TracerHttpRequestInterceptor`
  - `TracerAutoConfiguration`
  - `tracer` configuration namespace (Spring Boot)
- OpenTracing has its own concept and overloaded term of a `Tracer`, hence the *switch* to **_Flow_*.  
  The name is **not used consistently** right now:
  - `tracer` repositoriy :boom:
  - `tracer-*` modules and artifacts :boom:
  - `org.zalando.tracer` package :boom:
  - `Flow` main API
  - `FlowFilter`
  - `FlowHttpRequestInterceptor`
  - `TracerAutoConfiguration` :boom:
  - `tracer` configuration namespace (Spring Boot) :boom:

**Comment by whiskeysierra** [comment]
Once we remove the log correlation feature (new library already in the works) then the only responsibility left in this library is legacy flow-id handling.

My suggestion to rename this to `legacy-flow`.

**Comment by whiskeysierra** [comment]
(Library could become closed source since there is virtually no use case for this outside of Zalando.)

**Comment by fatroom** [comment]
`legacy-flow` sounds good to me. As well fine with moving to closed source

**Comment by whiskeysierra** [comment]
Superseded by #328
