### ISSUE TITLE
Could we please have some Javadocs?

### ISSUE THREAD

**Issue by ePaul** [zalando/tracer#29]
At least for the public interfaces which are meant to be used by programmers, each method should have one or two sentences saying what they are doing.

(For example, I've seen the `forEach` and `delegate` methods, but I don't understand what they are supposed to be doing.)

**Comment by whiskeysierra** [comment]
Totally agree, that would make the library a lot more usable.

**Comment by whiskeysierra** [comment]
@ePaul I just deployed [0.5.0](https://github.com/zalando/tracer/releases/tag/0.5.0) to central.
