### ISSUE TITLE
mdcTracer fails with NoopTracer instance

### ISSUE THREAD

**Issue by fatroom** [zalando/tracer#292]
## Description
In case client application doesn't have properly configured tracer and uses NoopTracer instance it will fail during incoming http call with 500 error.

## Expected Behavior
Incoming http call should pass FlowFilter and reach application business logic.

## Actual Behavior

Following exception thrown:
```
java.lang.NoSuchMethodError: io.opentracing.ScopeManager.active()Lio/opentracing/Scope;
	at io.opentracing.contrib.api.tracer.APIExtensionsTracer.activeSpan(APIExtensionsTracer.java:65)
	at io.opentracing.util.GlobalTracer.activeSpan(GlobalTracer.java:209)
	at io.opentracing.contrib.api.tracer.APIExtensionsTracer.activeSpan(APIExtensionsTracer.java:63)
	at org.zalando.tracer.DefaultFlow.activeSpan(DefaultFlow.java:75)
	at org.zalando.tracer.DefaultFlow.readFrom(DefaultFlow.java:23)
	at org.zalando.tracer.servlet.FlowFilter.doFilter(FlowFilter.java:25)
	at org.zalando.tracer.servlet.HttpFilter.doFilter(HttpFilter.java:28)
```

## Steps to Reproduce

The problem resides in utilising APIExtensionsTracer which is incompatible with OpenTracing-api 0.33.0.

Can be exposed by following test:
```
package org.zalando.tracer;

import io.opentracing.contrib.api.tracer.APIExtensionsTracer;
import io.opentracing.noop.NoopTracerFactory;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertThrows;

class DefaultFlowNoopTracerTest {
    private final APIExtensionsTracer tracer = new APIExtensionsTracer(NoopTracerFactory.create());
    private final Flow unit = Flow.create(tracer);

    @Test
    void shouldThrowNoActiveSpanFoundException() {
        assertThrows(IllegalStateException.class, unit::currentId);
    }
}
```

## Your Environment

* Version used: 2.0.0-RC.2
* Link to your project:

**Comment by fatroom** [comment]
Created fix as opentracing-contrib/java-api-extensions#21
If PR above will be accepted we'll need to update dependency to the new released version.

**Comment by whiskeysierra** [comment]
It's probably about time to roll our own version of java-api-extensions. The library ecosystem around opentracing is brittle enough as it is already. We should go with as little external dependencies as possible until the breaking API changes on OpenTracing settle down.
