### ISSUE TITLE
Expose http client request interceptors in TracerAutoConfiguration

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/tracer#37]
Using the following name:
- tracerHttpRequestInterceptor

**Comment by JonasJurczok** [comment]
Question regarding this:
Why are you just exposing the interceptor and not adding it to the httpClient automatically?

**Comment by whiskeysierra** [comment]
There is no http client to add it to. That's the task of https://github.com/zalando-incubator/put-it-to-rest.

**Comment by JonasJurczok** [comment]
Ah okay. I perceived them as more independent from each other. That explains everything, though. Thanks.

**Comment by whiskeysierra** [comment]
Well, *Tracer* is independent of *Put it to REST!*, but not the other way around.
