### ISSUE TITLE
Implement request-response 'weave' pattern logging

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/tracer#66]
Implement request-response 'weave' pattern logging which gives human readable way to follow correlated request-response log statements and concurrent request-response interleaving.

Idea is borrowed from here : https://pablosichert.github.io/concurrency-logger/
```
──‣ ┈┈┈┈┈ GET┈ ┬┈│┈│┈┈┈│┈┈ /
──‣ ┈┈┈┈┈ GET┈ │┈│┈│┈┬┈│┈┈ /
──‣ ┈┈┈┈┈ GET┈ │┈│┈│┈│┈│┈┬ /
200 ┈11ms GET┈ │┈┴┈│┈│┈│┈│ /
200 ┈┈4ms GET┈ │┈┈┈│┈│┈┴┈│ /
200 ┈┈6ms GET┈ │┈┈┈┴┈│┈┈┈│ /
──‣ ┈┈┈┈┈ GET┈ │┈┬┈┈┈│┈┈┈│ /
──‣ ┈┈┈┈┈ GET┈ │┈│┈┬┈│┈┈┈│ /
200 ┈┈5ms GET┈ │┈│┈┴┈│┈┈┈│ /
──‣ ┈┈┈┈┈ GET┈ │┈│┈┬┈│┈┈┈│ /
200 ┈21ms GET┈ │┈│┈│┈│┈┈┈┴ /
200 ┈27ms GET┈ │┈┴┈│┈│┈┈┈┈ /
──‣ ┈┈┈┈┈ GET┈ │┈┬┈│┈│┈┈┈┈ /
──‣ ┈┈┈┈┈ GET┈ │┈│┈│┈│┈┬┈┈ /
200 ┈42ms GET┈ │┈│┈│┈┴┈│┈┈ /
200 ┈23ms GET┈ │┈│┈┴┈┈┈│┈┈ /
200 ┈46ms GET┈ ┴┈│┈┈┈┈┈│┈┈ /
```

One possible (?) way is to store in logging context current weave pattern and log it as a part of logline along with flow-id 
```
{TRACE} [XNIO-3 task-4] [R595UgNfSHSq0vDzTZsoMw] [│┈│┈┴┈┈┈│┈┈] [org.zalando.logbook.Logbook] {"origin":"remote","type":"response"...
``` 

The referenced implementation uses coloring and multiline log statements which could be omitted for initial implementation.

**Comment by whiskeysierra** [comment]
I played around with the page you linked but I can't figure out what all the lines should tell me.

**Comment by AlexanderYastrebov** [comment]
You can easily follow request from response and vise versa as you can also see specific concurrent responses at any logged point in time

**Comment by whiskeysierra** [comment]
How do I know which of those lines belongs to the current log line? It's definitely not easy, at least not to me.
